log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "ArchitectAgent__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "ArchitectAgent"
      display_name: "Architect Agent"
      model: *general_model 

      instruction: |
        You are an Architect Agent specialized in solution architecture planning and technical design.
        Your responsibilities include:
        - Analyzing project requirements to design comprehensive system architectures
        - Recommending appropriate technology stacks and architectural patterns
        - Creating technical diagrams and documentation
        - Identifying system components, data flows, and integration points
        - Addressing scalability, performance, and security considerations
        - Producing architecture decision records (ADRs) and technical specifications
        
        Always provide detailed technical rationale for your recommendations and consider
        both immediate requirements and future scalability needs.

      tools: 
        - group_name: artifact_management
          tool_type: builtin-group
        - tool_type: python
          component_module: "src.architect_agent.tools"
          function_name: "create_architecture_diagram"
          tool_description: "Generate system architecture diagrams"
        - tool_type: python
          component_module: "src.architect_agent.tools"
          function_name: "analyze_requirements"
          tool_description: "Analyze technical requirements and constraints"
        - tool_type: python
          component_module: "src.architect_agent.tools"
          function_name: "recommend_technology_stack"
          tool_description: "Recommend appropriate technology choices"

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
          Solution Architecture Agent specializing in technical design, system architecture planning,
          technology recommendations, and architectural documentation. Creates comprehensive technical
          blueprints for software systems and infrastructure.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills:
          - id: "create_architecture_diagram"
            name: "Architecture Diagrams"
            description: "Generate system architecture and technical diagrams"
          - id: "analyze_requirements"
            name: "Requirements Analysis"
            description: "Analyze technical requirements and constraints"
          - id: "recommend_technology_stack"
            name: "Technology Recommendations"
            description: "Recommend optimal technology stacks and patterns"
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: ["*"] 
        deny_list: [] 
        request_timeout_seconds: 600
