# Solace Agent Mesh Agent Configuration

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "HiringAgent__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "HiringAgent"
      display_name: "Hiring Agent"
      model: *general_model

      instruction: |
        You are a Hiring Manager Agent specialized in job descriptions and candidate screening workflows.
        Your responsibilities include:
        - Creating comprehensive job descriptions based on project requirements
        - Defining required skills, qualifications, and experience levels
        - Developing candidate screening criteria and interview processes
        - Designing assessment frameworks for technical and soft skills
        - Creating job posting content optimized for different platforms
        - Analyzing team composition needs and role requirements
        
        Focus on creating clear, inclusive, and effective hiring materials that attract
        the right talent while ensuring fair and comprehensive evaluation processes.

      tools:
        - group_name: artifact_management
          tool_type: builtin-group
        - tool_type: python
          component_module: "src.hiring_manager.tools"
          function_name: "create_job_description"
          tool_description: "Generate comprehensive job descriptions"
        - tool_type: python
          component_module: "src.hiring_manager.tools"
          function_name: "design_screening_process"
          tool_description: "Design candidate screening and interview processes"
        - tool_type: python
          component_module: "src.hiring_manager.tools"
          function_name: "analyze_team_needs"
          tool_description: "Analyze team composition and role requirements"

      session_service: *default_session_service
      artifact_service: *default_artifact_service

      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
          Hiring Manager Agent specializing in recruitment strategy, job description creation,
          candidate screening processes, and team composition analysis. Designs comprehensive
          hiring workflows and assessment frameworks.
        defaultInputModes: [text]
        defaultOutputModes: [text, file]
        skills:
          - id: "create_job_description"
            name: "Job Description Creation"
            description: "Generate comprehensive and effective job descriptions"
          - id: "design_screening_process"
            name: "Screening Process Design"
            description: "Design candidate screening and interview workflows"
          - id: "analyze_team_needs"
            name: "Team Needs Analysis"
            description: "Analyze team composition and role requirements"

      # Discovery & Communication
      agent_card_publishing:
        interval_seconds: 10
      agent_discovery:
        enabled: true
      inter_agent_communication:
        allow_list: ["*"]
        deny_list: []
        request_timeout_seconds: 600