log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "ProgramManagerAgent__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "ProgramManagerAgent"
      display_name: "Program Manager Agent"
      model: *general_model 

      instruction: |
        You are a Program Manager Agent specialized in project coordination and milestone management.
        Your responsibilities include:
        - Creating comprehensive project plans with clear milestones and deliverables
        - Coordinating work between multiple teams and stakeholders
        - Managing project timelines, dependencies, and resource allocation
        - Tracking progress and identifying potential risks or blockers
        - Facilitating communication and collaboration across teams
        - Creating status reports and project documentation
        - Managing scope changes and stakeholder expectations
        
        Focus on ensuring projects are delivered on time, within scope, and meet quality standards
        while maintaining clear communication and accountability across all participants.

      tools: 
        - group_name: artifact_management
          tool_type: builtin-group
        - tool_type: python
          component_module: "src.program_manager_agent.tools"
          function_name: "create_project_plan"
          tool_description: "Create detailed project plans with milestones"
        - tool_type: python
          component_module: "src.program_manager_agent.tools"
          function_name: "track_project_progress"
          tool_description: "Monitor and track project progress and metrics"
        - tool_type: python
          component_module: "src.program_manager_agent.tools"
          function_name: "manage_stakeholders"
          tool_description: "Coordinate stakeholder communication and expectations"

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
          Program Manager Agent specializing in project coordination, milestone management,
          and cross-team collaboration. Creates comprehensive project plans, tracks progress,
          and ensures successful delivery of complex initiatives.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills:
          - id: "create_project_plan"
            name: "Project Planning"
            description: "Create detailed project plans with milestones and deliverables"
          - id: "track_project_progress"
            name: "Progress Tracking"
            description: "Monitor project progress and identify risks or blockers"
          - id: "manage_stakeholders"
            name: "Stakeholder Management"
            description: "Coordinate communication and manage expectations"
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: ["*"] 
        deny_list: [] 
        request_timeout_seconds: 600
