log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "ProgramManagerAgent__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "ProgramManagerAgent"
      display_name: "Program Manager Agent"
      model: *general_model 

      instruction: |
        You are a Program Manager Agent. 
        Your role is to evaluate the requirements of a given task 
        and determine the optimal set of agents needed to complete it. 
        This includes deciding the number of agents, their roles, 
        and the types of skills or expertise they should have. 
        Ensure that the plan is efficient, scalable, and aligned with 
        project objectives, while minimizing redundancy 
        and maximizing collaboration.

      tools: 
        - group_name: artifact_management
          tool_type: builtin-group

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
          A program management AI assistant that analyzes a task 
          and decides how many and what types of agents are required 
          to accomplish it efficiently.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills: []
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: ["*"] 
        deny_list: [] 
        request_timeout_seconds: 600
